#!/usr/bin/env bash
#
# build_and_tag.sh — Build an Ansible module, tag a release, and push to GitHub.
#

set -euo pipefail

# ------------------------
# CONFIGURATION VARIABLES
# ------------------------

# Default version tag if none provided
DEFAULT_TAG="v$(date +%Y.%m.%d.%H%M)"

# Path to your Ansible collection (adjust as needed)
COLLECTION_PATH="."

# Whether to build the collection
BUILD_COLLECTION=true

# ------------------------
# FUNCTIONS
# ------------------------

clean_old_builds() {
    echo "🧹 Cleaning old build artifacts..."
    find "$COLLECTION_PATH" -maxdepth 1 -type f -name "*.tar.gz" -print -delete || true
}

build_collection() {
    echo "📦 Building Ansible collection..."
    clean_old_builds
    ansible-galaxy collection build "$COLLECTION_PATH"
}

create_tag() {
    local tag=${1:-$DEFAULT_TAG}
    if git rev-parse "$tag" >/dev/null 2>&1; then
        echo "⚠️  Tag '$tag' already exists. Skipping tag creation."
    else
        echo "🏷  Creating Git tag: $tag"
        git tag -a "$tag" -m "Release $tag"
    fi
}

push_git() {
    local tag=${1:-$DEFAULT_TAG}
    local branch
    branch=$(git rev-parse --abbrev-ref HEAD)
    echo "🚀 Pushing commits and tag to origin on branch '$branch'..."
    git push origin "$branch"
    git push origin "$tag"
}

usage() {
    echo "Usage: $0 [-t TAG] [-s] [-p PATH]"
    echo
    echo "Options:"
    echo "  -t TAG     Specify a git tag name (default: autogenerated)"
    echo "  -s         Skip collection build step"
    echo "  -p PATH    Path to Ansible collection (default: current directory)"
    exit 1
}

# ------------------------
# MAIN SCRIPT
# ------------------------

TAG=""
while getopts "t:sp:" opt; do
    case $opt in
        t) TAG="$OPTARG" ;;
        s) BUILD_COLLECTION=false ;;
        p) COLLECTION_PATH="$OPTARG" ;;
        *) usage ;;
    esac
done

if $BUILD_COLLECTION; then
    build_collection
else
    echo "⏭️  Skipping build step..."
fi

create_tag "$TAG"
push_git "$TAG"

echo "✅ Done. Tag '$TAG' pushed successfully."
